#baseURL = "http://localhost:1313/"
baseURL = "https://marlinspike.github.io/sharpentity.github.io/"
title = "SharpEntity"
author = "rcleetus"
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "ananke"
enableRobotsTXT = true

[params]
  description = "SharpEntity - Your trusted partner for technology solutions."
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
  [[menu.main]]
    name = "Services"
    pageRef = "/services"
    weight = 20
  [[menu.main]]
    name = "GenAI"
    parent = "Services"
    pageRef = "/services/genai"
    weight = 25
  [[menu.main]]
    name = "Cloud Migration"
    parent = "Services"
    pageRef = "/services/cloud-migration"
    weight = 30
  [[menu.main]]
    name = "Architecture and Design"
    parent = "Services"
    pageRef = "/services/architecture-design"
    weight = 35
  [[menu.main]]
    name = "Strategic Consulting"
    parent = "Services"
    pageRef = "/services/strategic-consulting"
    weight = 40
  [[menu.main]]
    name = "Leadership"
    pageRef = "/leadership"
    weight = 50
  [[menu.main]]
    name = "Contact"
    pageRef = "/contact"
    weight = 40

